### ISSUE TITLE
Brave Custom Policies

### ISSUE THREAD

**Issue by Prowler2** [Prowler2/Brave-Browser-GPO-Policy#2]
Create new policy folder for all Brave specific custom policies. Create all current and future Brave specific policies under this new folder.  TOR and IPFS are the only ones for now. 

https://support.brave.com/hc/en-us/articles/360039248271-Group-Policy

**Comment by EHRETic** [comment]
Hi :-)

Posted something in https://github.com/brave/brave-browser/issues/9458 but it is better to have it here for better tracking.

It seems we miss the GPO setting for "_Automatically send completely private product analytics to Brave This anonymous info only lets Brave estimate the overall usage of certain features._".

I may discover some others day after day 😉

**Comment by Prowler2** [comment]
Added policy folder for all current and future Brave Browser specific policies. Moved TOR and IPFS settings to this folder.
