### ISSUE TITLE
WMI filter not working depending when you installed Brave

### ISSUE THREAD

**Issue by EHRETic** [Prowler2/Brave-Browser-GPO-Policy#4]
Hi there,

I've noticed the WMI filter might not work depending when you installed Brave.
Starting from some version, it installs now in **C:\Program Files** and not in **C:\Program Files (x86)** anymore (Chrome was the same)

Therefore, we can adjust the WMI filter to cover both install folders this way:

`SELECT Name FROM CIM_Datafile WHERE Name = 'C:\\Program Files\\BraveSoftware\\Brave-Browser\\Application\\brave.exe' OR Name = 'C:\\Program Files (x86)\\BraveSoftware\\Brave-Browser\\Application\\brave.exe'`

**Comment by Prowler2** [comment]
Appreciate the feedback. I'll make this change in the next update. This must be a change if newly installed that does not affect if you only upgrade or update. I noticed mine is still located in `C:\Program Files (x86)\BraveSoftware\Brave-Browser\Application`

**Comment by EHRETic** [comment]
You're welcome!😉
I can confirm : I had an old install: it doesn't change it, it keeps it in x86 folder. 
(Same behavior for Chrome BTW and for both it was a long time bug)

And for the feedback, it is the least I can do. You did most of the work and I appreciate it a lot!! 😄

**Comment by Prowler2** [comment]
Updated WMI filter to detect brave installations in C:\program files or C:\program files (x86)
