### ISSUE TITLE
WMI Filter fails to import

### ISSUE THREAD

**Issue by virtualex-itv** [Prowler2/Brave-Browser-GPO-Policy#5]
This .mof fails to import with the error:
`The file does not contain a valid WMI filter`

Also, per this [issue](https://github.com/Prowler2/Brave-Browser-GPO-Policy/issues/4), i tried to manually create the filter, but when tested using the WMI Filter Validator, I receive:
 `WMI Filter evaluates to FALSE on target...`.

If installed, this should report back TRUE if successfully validated right?

**Comment by Prowler2** [comment]
I was able to duplicate your error with importing the filter. I uploaded a new MOF that imports without error into a Server 2019 DC on my end. The new filter also returns TRUE if run against a client that has Brave installed. Try this new file and let me know if this fixes the issue.
